name: Test Pull Request

on: [pull_request]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Copy mock google_services.json
        run: cp mock-google-services.json sampleapp/google-services.json
      - name: Run Tests with gradle
        run: ./gradlew clean testDebugUnitTest check
